### ISSUE TITLE
当通配符证书基础域名为三级域名或以上时会报错

### ISSUE THREAD

**Issue by tgly307** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#11]
感谢该工具，解决了VPS证书自动续期的问题。
不过有个小问题，我的通配符域名是位于三级域名下，例如`*.abc.github.com`，这样直接使用php脚本会有问题，因为腾讯云的接口默认domain只识别二级域名。需要在脚本入口处做一些处理，把传入的前两个参数做一下拼接以适应腾讯云的接口即可。
```php
$global_domain = $argv[1];
$global_subdomain = $argv[2];
$list = explode(".",$argv[1]);
$n = count($list);
if ($n>2) {
	$global_domain = $list[$n-2].".".$list[$n-1];
	$global_subdomain = $argv[2];
    for($i=0; $i<$n-2;$i++) {
        $global_subdomain = $global_subdomain.".".$list[$i];
    }
}
```
以上是我自己做的修改部分，在后续引用时，使用两个global变量就可以了。我自己测试可以正常更新解析，但是对php比较陌生，不知道写法上是否有纰漏，如果没有问题我再提pr。

**Comment by ywdblog** [comment]
这个问题我确实没有想到，感谢。

我没有测试，以下简单猜测：
sh 传递过来的应该是完整域名，比如主机 a.b.github.com （a.b.github.cn），传递给类的时候，等于 $argv[1]要取出根域名，其他的应该不用改。

**Comment by tgly307** [comment]
第二个参数也是要改的，不然就会更新到根域名对应的TXT记录上去。
举个例子，如果要renew的是`*.a.b.com`的证书，传给腾讯云的`domain`应该是`b.com`，对应的`subdomain`则应该是`_acme-challenge.a`。所以要把sh传给php的前两个参数都做处理，把第一个参数中的二级以上域名部分都拼接到`_acme-challenge`上去

**Comment by ywdblog** [comment]
好像改动还挺大，你 renew *.a.b.com ，传递给那个php 文件的三个参数分别是什么

**Comment by tgly307** [comment]
shell传递给php文件的参数是没变的，仍然是 a.b.com、_acme-challenge、xxxvalue 
参数的处理过程在php里。改动只是在使用类TxyDns的时候，参数变为b.com、_acme-challenge.a、xxxvalue而已。
我贴一下我改后的调用部分，TxyDns类和shell文件完全不需要改动。
```php
$global_domain = $argv[1];
$global_subdomain = $argv[2];
$list = explode(".",$argv[1]);
$n = count($list);
if ($n>2) {
	$global_domain = $list[$n-2].".".$list[$n-1];
	$global_subdomain = $argv[2];
    for($i=0; $i<$n-2;$i++) {
        $global_subdomain = $global_subdomain.".".$list[$i];
    }
}



$obj = new TxyDns(txyaccessKeyId, txyaccessSecrec, $global_domain);
$data = $obj->RecordList($global_subdomain, "TXT");
if ($data["code"] != "0") {
    $obj->error($data["code"], $data["message"]);
}

$records = $data["data"]["records"];
foreach ($records as $k => $v) {
    // 如果存在记录，则直接修改。
    if ($v["name"] == $global_subdomain) {
		echo $v["name"]."\n";
        $data = $obj->RecordModify($global_subdomain, "TXT", $argv[3], $v["id"]);
        if ($data["code"] != "0") {
            $obj->error($data["code"], $data["message"]);
        }
        //$obj->RecordDelete($v["id"]);
        exit;
    }
}
//如果不存在，就增加 TXT 记录
$data = $obj->RecordCreate($global_subdomain, "TXT", $argv[3]);
if ($data["code"] != "0") {
    //失败，则记录日志
    $obj->error($data["code"], $data["message"]);
}
```

**Comment by tgly307** [comment]
简单来说就是原来使用agrv[1]、[2]的地方改为处理后的global_domain和global_subdomain而已

**Comment by ywdblog** [comment]
感谢。保持类不变确实是正道。

不过如果一个根域名是 .com.cn 这样结尾的，有些问题。

你  a.b.com 这样我常规叫他二级域名（也就是你想未一个二级域名申请证书）。（b.com 算主域名），这个只是为了保证我们沟通一致就行。

**Comment by tgly307** [comment]
嗯……确实是这样，不知道腾讯对根域名的判断是什么样的。
不过乐观的想，一般用到LE通配符的证书的应该大部分是a.com的形式，在没有解决方案之前可以在文档中标明对于根域名长度的判断逻辑，用户根据自己的需要来手工调整。

**Comment by ywdblog** [comment]
1：阿里云DNS 估计也是这样的，这应该是标准的，对根域名进行 RR 设置。
2：正确匹配出根域名，我也想想办法。

感谢，确实我开始没想到。

**Comment by tgly307** [comment]
我觉得单纯靠脚本解决不了所有奇葩域名。这个[主域名的列表](https://publicsuffix.org/list/public_suffix_list.dat)列出了目前一些已知的根域名。
前端有个解决方案是根据cookie来逐步测试，原理应该是浏览器会根据域名服务器解析结果识别根域名。
所以我觉得吧……这个坑可以先缓缓，不妨做成配置项让用户来输入。

**Comment by tgly307** [comment]
我目前是用多个shell配合来完成全自动续期的，auth-hook部分直接用本项目修改后的shell和php，然后再外层再套一层shell来调用certbot-auto，我想在这一层可以让用户做一些参数的设置。
手动改造也可以，反正这些设置好了都是丢到计划任务里一劳永逸的。

**Comment by ywdblog** [comment]
1：他这个hook文件（.sh）不能接收其他参数（只能接收certbit 传递的系统参数），所以可控程度确实不好。
2：作为工具，我的本意是想尽量对用户来说简单一点，配置太多，解释不清，大家也就不愿意用了。
3：实在不行，我就列举主流的根域名。你发的那个网址列举的太多了，最好有常用的就行了。

**Comment by tgly307** [comment]
简单一点可以让用户把根域名写进php里嘛，像key一样写进去就好了，也就3个参数要配置。

**Comment by ywdblog** [comment]
修复了下，可以看看。

**Comment by tgly307** [comment]
嗯，常见域名都有应该能覆盖大部分情况了。如果有特殊需要再加好了。
