### ISSUE TITLE
执行了一下au.sh 的方式，有一个交互过程，定时执行的时候会有问题吧？我shell不行，大拿支持一下

### ISSUE THREAD

**Issue by qinweixian** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#12]
`[root@VM_0_15_centos certbot]# ./certbot-auto certonly  -d *.qinweixian.com --manual --preferred-challenges dns  --manual-auth-hook /data/www/certbot-letencrypt-wildcardcertificates-alydns-au/au.sh --dry-run
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Cert not due for renewal, but simulating renewal for dry run
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for qinweixian.com

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
NOTE: The IP of this machine will be publicly logged as having requested this
certificate. If you're running certbot in manual mode on a machine that is not
your server, please ensure you're okay with that.

Are you OK with your IP being logged?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o: y
Output from au.sh:
/data/www/certbot-letencrypt-wildcardcertificates-alydns-au/alydns.php
qinweixian.com_acme-challengeRuxxvRN2ss0eOxZBfzgQbDw8xgB9EgZhkBbJdr46Uww
END

Waiting for verification...
Cleaning up challenges

IMPORTANT NOTES:
 - The dry run was successful.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.`

**Comment by ywdblog** [comment]
不会有问题，在新建证书，它需要你确认一些信息，在 renew 的时候，它就无需确认了，放心把，你成功申请后，可以运行下面的 renew 测试下。
