### ISSUE TITLE
大佬可否为dnspod国际版增加一下支持呢？

### ISSUE THREAD

**Issue by rickly** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#14]
dnspod国际版目前脚本支持的很少，不知道大佬可否能增加一下支持呢？不胜感激！
下面是国际版API的官方文档https://www.dnspod.com/docs/index.html

**Comment by ywdblog** [comment]
dnspod国内版其实已经整合到腾讯云了，国际版刚才看了下，提示“DNSPod 国际版解析业务暂停维护”，我觉得比较小众了，暂时不打算支持了，抱歉。
