### ISSUE TITLE
Let's encrypt的通配符证书无法匹配多层级子域名

### ISSUE THREAD

**Issue by huangyonghome** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#15]
我的证书是*.dev.xxx.com
我的nginx站点域名是:api.v3.dev.xxx.com
所有配置都正确,但是浏览器无法匹配api.v3.dev.xxx.com域名.所以还需要申请*·v3.dev.xxx.com的证书 通配符只能匹配一个层次的主机域名

那请问有没有什么方式能一张证书适应所有的子域名呢? 比如我有以下子域名:
api.dev.xxx.com
api.v3.dev.xxx.com
api.v4.dev.xxx.com
open.devapi.xxx.com
(注意:xxx.com是一致的)

**Comment by ywdblog** [comment]
参考 README.md 

```
$ ./certbot-auto certonly  -d *.dev.xxx.com -d *.v3.dev.xxx.com -d *.v4.dev.xxx.com  --manual --preferred-challenges dns  --manual-auth-hook /脚本目录/au.sh  --dry-run
```

**Comment by huangyonghome** [comment]
这个方法其实还是相当于申请了3张通配符域名证书?

**Comment by ywdblog** [comment]
一张，叫做SAN通配符证书，SAN可以理解为一张证书包含多个主机，通配符是适配某个主机的所有子域名（一级）。
