### ISSUE TITLE
请问是否支持DNSPORT?

### ISSUE THREAD

**Issue by huangyonghome** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#16]
请问是否支持dnsport???

**Comment by ywdblog** [comment]
DNSPod吧？目前这个工具支持阿里云 DNS 和腾讯云 DNS（DNSpod被通讯购买了，所以不管在腾讯云还是DNSPod国内版，实际上操作的就是腾讯云 DNS）。你说的 DNSPod 应该指的是 DNSPod 国际版，这个目前不支持。

**Comment by huangyonghome** [comment]
不是国际版..腾讯云确实也能看到DNSPOD的域名解析..
DNSPord有个API Token.
腾讯云也有API的ID和secret.

请问DNSPord的API Token是否可以?? 还是说一定要用腾讯云的API

**Comment by ywdblog** [comment]
你可以都登陆进去（腾讯云和DNSPod）看看，数据都是相同的。

**Comment by huangyonghome** [comment]
另外一个问题..请问下面这个autxy.sh的echo语句.这里echo的是alydns.php.是否有误
```
root@docker:~/certbot-wildcard# cat autxy.sh
#!/bin/bash

# 腾讯云操作 DNS Hook

PATH=$(cd `dirname $0`; pwd)

echo $PATH"/alydns.php"
```

**Comment by ywdblog** [comment]
这是打印路径，不是执行php程序。

**Comment by huangyonghome** [comment]
非常感谢您的解答.目前证书都没有小于30天的.我后期继续观察一下.

**Comment by ywdblog** [comment]
可以加一个cron，执行自动续期。
