### ISSUE TITLE
关于python3

### ISSUE THREAD

**Issue by ghost** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#18]
certbot-letencrypt-wildcardcertificates-alydns-au/python-version/au.sh文件中写死了文件路径为alydns27.py，对于在使用python3的情况下，没有判断来执行alydns36.py。

这是个小问题，可以手动改一下代码解决。

**Comment by ywdblog** [comment]
好的，我最近修改下

**Comment by ywdblog** [comment]
解决了，同时兼容python2/3，不用指定版本了。

另外python版本，针对**非二级根域名**还有些bug（php版本没有），后续会修改。
