### ISSUE TITLE
报错：-bash: ./bin/start.sh: /bin/bash^M: bad interpreter: No such file or directory 问题

### ISSUE THREAD

**Issue by EasonPro** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#20]
原因是 文件的格式是dos,修改为unix 就OK了

具体操作步骤：
查看文件格式  用vim 打开出错的文件    按 ESC键     再按shift+冒号   输入 set  ff  回车   可以看见 该文件的格式 fileformat=dos
按shift + 冒号  输入  set ff=unix
可以按 shift + 冒号  set ff 查看  fileformat=unix

**Comment by ywdblog** [comment]
ok
