### ISSUE TITLE
多个不同级域名解析问题

### ISSUE THREAD

**Issue by hellohappy0** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#21]
多个不同级域名解析时候，比如 example.com 和 *.example.com ，会出现多次改写域名 txt的解析 ，最后校验不能通过。(因为 通配符域名 *.example.com 实际上是不包括 example.com这个域名在内的，所以我想一起给他打包了，后来发现不行？)不知道有木有解决办法。也不知道默认官方看同一个域名的第几个解析值？
1.我是确定我已经成功执行过一次并且得到正确的证书了，证书包含了  大概如下的example.com 、 *.example.com  、*.example2.com 三个泛域名。所以不是我别的操作有问题
2.出问题是在我尝试使用certbot-auto 更新证书时候(加了--dry-run)，报错说校验失败。更新证书时候，提示说要更新三次域名txt解析，其中有两条是对同一个域名的。

**Comment by ywdblog** [comment]
你说的第一个问题，是手动第一次生成证书吗，就是手动添加dns txt 记录吗？

**Comment by ywdblog** [comment]
另外是阿里云吗？

**Comment by hellohappy0** [comment]
不是 我是用阿里云api 自动生成证书的 ，用的是php版 ，而且执行成功了 ，不是手动的。

**Comment by ywdblog** [comment]
@hellohappy0 

我再确认下：
（1）你首先用这脚本申请了证书，包含 *.example.com example.com ,也是自动配置dns记录，这个成功了。

（2）续期的时候，同样的配置，但失败了，对吗？

**Comment by hellohappy0** [comment]
对的，同样的配置，只不过后者是续期，前者是申请。续期验证没通过，而且根据阿里云的提示，通过程序更改txt记录都是成功了的。

**Comment by ywdblog** [comment]
@hellohappy0 

1：按道理和我测试的结果，申请也不应该成功。
2：临时解决方法
你找到 alydns.php  ，将 ```$res = $obj->DeleteDomainRecord($v["RecordId"]);'``` 这行注释掉。

说明：
 alydns.php  在执行的时候会默认删除已存在的 TXT 记录，现在改为不删除，可以同时存在两条同名的记录。

这是一个临时的解决方案，其实 certbot 支持 cleanup hook （比如一个php程序），但这样会将这个小工具弄的太复杂，所以我再想一想。

**Comment by hellohappy0** [comment]
@ywdblog 嗯嗯 谢谢你的回复。根据你的回答(我可能理解不深，不过希望能对你有帮助)，我有一个思路大概是这样的：先删除已经存在的txt记录，然后在写txt记录前，记录下所有要写到同一个域名下的所有txt记录，然后再去写txt记录，这样应该就不会删掉前面的记录了吧？或者可以先写记录，执行完整个校验以后再去删记录？

**Comment by ywdblog** [comment]
alydns.php 只管执行，它不知道上下文，你说的虽然可行（记录所有同域名），但复杂化了，一个小工具想让它使用的时候简单点；关于第二个建议，可参考 https://mp.weixin.qq.com/s/oSjLOkumhjQIzzWVmRM_jA

**Comment by keminshu** [comment]
cleanup-hook need to resolve the follow issue:
![image](https://user-images.githubusercontent.com/10050045/53280100-9436aa80-3751-11e9-9126-5bb3315c8db8.png)

**Comment by kssion** [comment]
@ywdblog  同样的问题，我昨天用的时候也遇到了，然后我只改了python版本的代码，在我的电脑上测试一切正常，我等下发布一个拉取请求

**Comment by ywdblog** [comment]
#24 解决了

**Comment by ywdblog** [comment]
测试有问题，还请反馈我。

**Comment by ywdblog** [comment]
测试有问题，还请反馈
