### ISSUE TITLE
使用阿里云子账户(RAM)的access key 出问题

### ISSUE THREAD

**Issue by citizenll** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#22]
![image](https://user-images.githubusercontent.com/16896067/52832256-b5c0e200-3112-11e9-8ac1-86afc67551de.png)
如图，给了子账户域名全部权限，是不是子账户拿到的数据结构不一样？还是？

**Comment by ywdblog** [comment]
你这提供的信息太少了，如果你懂一点php，建议直接运行那个php代码，调试下

**Comment by citizenll** [comment]
@ywdblog 已解决，经测试是权限问题，之前以为只有 AliyunDomainFullAccess 这个权限就够了，后添加如下权限就好了

![image](https://user-images.githubusercontent.com/16896067/53139604-1ba2e300-35c5-11e9-84d1-b9e0d75ac82f.png)
