### ISSUE TITLE
腾讯云更新失败，总是报Challenge failed for domain ...

### ISSUE THREAD

**Issue by poaqaqaq** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#28]
看起来像是腾讯云的配置填错了，但是我确认过是正确的，请问该怎么解决呢？

**Comment by poaqaqaq** [comment]
Attempting to renew cert (young-marvelous.cn) from /etc/letsencrypt/renewal/young-marvelous.cn.conf produced an unexpected error: Some challenges have failed.. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/young-marvelous.cn/fullchain.pem (failure)
提示这个错误。。
这是 他给的建议：
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: young-marvelous.cn
   Type:   unauthorized
   Detail: No TXT record found at _acme-challenge.young-marvelous.cn

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

**Comment by poaqaqaq** [comment]
找到问题了。。。au.sh中，如果是php和腾讯云的环境的$path写成了小写，改成大写$PATH即可

**Comment by ywdblog** [comment]
非常感谢，最近重写，出现了点问题。
