### ISSUE TITLE
非--dry-run下不能更新_acme-challenge记录

### ISSUE THREAD

**Issue by zcqno1** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#29]
添加 `--dry-run` 可以看到 dns 的 _acme-challenge 记录值被更新
去掉 `--dry-run` 然后加上 `--force-renewal` 强制更新，显示证书更新成功，但查看 dns 的 _acme-challenge 记录值没有被更新，打印信息也没有脚本调用的记录（加 `--dry-run` 的有）

**Comment by ywdblog** [comment]
1：如果同时有 --force-renewal 和  --dry-run，这个要看certbot 内部运行优先级了，你可以看看输出提示什么，我猜测如果同时存在，可能 --force-renewal 应该是忽略的。
2：如果  --force-renewal，它看你证书没有过期，就认为不要 DNS 校验了，直接更新证书发你。

以上是猜测，希望有用。
