### ISSUE TITLE
au.sh里面只能配置一个域名吗

### ISSUE THREAD

**Issue by ToSsBoYs** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#3]
如果我的一个证书里面有多个不同的泛域名该怎么办

**Comment by ywdblog** [comment]
我测试下吧，没考虑这个问题。

**Comment by yudadan** [comment]
@ToSsBoYs 

测试了下，certbot 还是很职能的，输入两个 -d （代表给多个域名申请证书），certbot 会自动调用 alydns.php 两次，所以 renew 没有问题。

具体可查看最新的 README.md

**Comment by ywdblog** [comment]
@ToSsBoYs

测试了下，certbot 还是很职能的，输入两个 -d （代表给多个域名申请证书），certbot 会自动调用 alydns.php 两次，所以 renew 没有问题。

具体可查看最新的 README.md。
