### ISSUE TITLE
goDaddy 的是不是有问题啊.

### ISSUE THREAD

**Issue by 759434091** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#31]
变量完全不对应?

**Comment by ywdblog** [comment]
今天我弄一下。

**Comment by 759434091** [comment]
> 今天我弄一下。

变量错位了, php还是能用的. 感谢. 另外我的域名是 .blog , 脚本查询domain 查询少了

**Comment by ywdblog** [comment]
> > 今天我弄一下。
> 
> 变量错位了, php还是能用的. 感谢. 另外我的域名是 .blog , 脚本查询domain 查询少了

已经修复了，不过没有找到goDaddy 的删除dns记录 api，可能会有小问题（比如 为 example.com *.example.com）添加证书的时候，具体见 #21

**Comment by ywdblog** [comment]
> > > 今天我弄一下。
> > 
> > 
> > 变量错位了, php还是能用的. 感谢. 另外我的域名是 .blog , 脚本查询domain 查询少了
> 
> 已经修复了，不过没有找到goDaddy 的删除dns记录 api，可能会有小问题（比如 为 example.com *.example.com）添加证书的时候，具体见 #21

更新master即可。
