### ISSUE TITLE
发现个小问题

### ISSUE THREAD

**Issue by eaglepie** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#32]
你说明上写的是“certbot-auto”，一执行就出问题，正确写法是它们之间有个空格，如下：
certbot -auto

**Comment by ywdblog** [comment]
certbot-auto 是 certbot 的外壳程序，用于自动升级 certbot，用 certbot-auto 或  certbot 都可以运行。

另外我本机并没有 certbot 命令行，也许有 -auto 参数。

**Comment by eaglepie** [comment]
是有这个参数的，加个空格写就没问题了，不然的话，当成个命令了。
