### ISSUE TITLE
库找不到

### ISSUE THREAD

**Issue by MyLeoLan** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#36]
![image](https://user-images.githubusercontent.com/18298528/59170976-7ad83380-8b73-11e9-9e52-055d040bae57.png)

**Comment by ywdblog** [comment]
抱歉，无法做出判断。

**Comment by MyLeoLan** [comment]
你好，感想您的回复。

阿里云ECS环境：Centos7，自带python2，安装了python3；pip对应python2；pip3对应python3。
执行续期就会报上面的错误。

Docker环境中：Debian 9（python3.6.8镜像），申请证书，续签证书都会报以下错误，
![image](https://user-images.githubusercontent.com/18298528/59199899-9ff79100-8bc9-11e9-8e9d-d1a14626da5f.png)
![image](https://user-images.githubusercontent.com/18298528/59199953-c4536d80-8bc9-11e9-8e99-af85829089ec.png)
默认安装的pytz也不行，图中的pytz是换成了最新的版本。


最后，我发现无法创建TXT记录，可以确认不是密钥问题，2个月前配置一直没动过；使用了两组密钥依然不行。

**Comment by ywdblog** [comment]
```
 (tutorial-env) root@ns:~# pip3 list        
Package    Version
---------- -------
pip        10.0.1 
pytz       2019.1 
setuptools 39.0.1 
```

python alydns.py add  你的域名, xx ,yy ,ACCESS_KEY_ID, ACCESS_KEY_SECRET 

你运行看看

**Comment by ywdblog** [comment]
改了下程序，去除 pytz 库的引用

**Comment by MyLeoLan** [comment]
感谢大佬及时处理，忙了好几天，今天试了下问题依旧，可能是我的环境有问题，我有空尝试修改源码；个人觉得没必要兼容python2了。
