### ISSUE TITLE
php 脚本三级子域名添加 txt 记录错误

### ISSUE THREAD

**Issue by ethsonliu** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#38]
比如三级子域名：`ni.hao.me.com`。

最后会报错：`No TXT record found at`.

然后我到阿里后台观察到，你漏了个点。

```
主机记录
_acme-challenge.nihao
```

`nihao`中间的点没了，导致验证失败。

**Comment by ywdblog** [comment]
你的根域是什么？  在下面这个列表中吗？

       $arr[] = ".co.jp";
        $arr[] = ".com.tw";
        $arr[] = ".net";
        $arr[] = ".com";
        $arr[] = ".com.cn";
        $arr[] = ".org";
        $arr[] = ".cn";
        $arr[] = ".gov";
        $arr[] = ".net.cn";
        $arr[] = ".io";
        $arr[] = ".top";
        $arr[] = ".me";
        $arr[] = ".int";
        $arr[] = ".edu";
        $arr[] = ".link";
        $arr[] = ".uk";
        $arr[] = ".hk";

**Comment by ethsonliu** [comment]
在，是.net

**Comment by ywdblog** [comment]
感谢，有bug，我改了 php aly 版本，观察无问题后，我再改其他的，git pull 拉取最新即可。

**Comment by ethsonliu** [comment]
@ywdblog 
我这边测试没问题。
