### ISSUE TITLE
ValueError: need more than 5 values to unpack

### ISSUE THREAD

**Issue by HerbertHe** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#49]
选择hook shell的时候，alydns.py报错 ValueError: need more than 5 values to unpack
debug:

```python
print(sys.argv)
```

输出的参数只有五个，但是解析7个，是不是缺少certbot_domain和certbot_validation这两个参数？？？

**Comment by ywdblog** [comment]
你au.sh里面的token 两个值填写了吗

**Comment by HerbertHe** [comment]
写了

**Comment by ywdblog** [comment]
你调用语句发下呢

**Comment by HerbertHe** [comment]
```bash
./au.sh python aly add/clean
```

**Comment by ywdblog** [comment]
# 实际申请
$ ./certbot-auto certonly  -d *.example.com --manual --preferred-challenges dns --manual-auth-hook "/脚本目录/au.sh php aly add" --manual-cleanup-hook "/脚本目录/au.sh php aly clean"

**Comment by HerbertHe** [comment]
嗷嗷这一步不用做是吧，直接修改后面的，谢谢

**Comment by HerbertHe** [comment]
那个certbot-auto这个命令好像不能用了，直接certbot就可以了

**Comment by ywdblog** [comment]
certbot-auto 是certbot的外壳程序 可以认为是同一个
