### ISSUE TITLE
会不会误删有用的A记录

### ISSUE THREAD

**Issue by joyexpr** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#50]
简单看了下文档和代码，好像删除dns记录时没有限制只删txt类型的，担心会不会把有用的A记录给误删？

**Comment by ywdblog** [comment]
不会 在你主机前会加一个随机的变量

**Comment by joyexpr** [comment]
好的，谢谢 😊





------------------ 原始邮件 ------------------
发件人: 虞大胆 <notifications@github.com>
发送时间: 2019年8月2日 21:01
收件人: ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au <certbot-letencrypt-wildcardcertificates-alydns-au@noreply.github.com>
抄送: joyexpr <joyexpr@qq.com>, Author <author@noreply.github.com>
主题: 回复：[ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au] 会不会误删有用的A记录 (#50)




不会 在你主机前会加一个随机的变量
