### ISSUE TITLE
手动跑这个脚本的提示Are you OK with your IP being logged?，需要输入yes/no

### ISSUE THREAD

**Issue by junly917** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#51]
是需要添加额外的参数还是怎么样？使用的命令和输出如下：
./certbot-auto certonly -d *.xx.com --manual --preferred-challenges dns  --manual-auth-hook "/home/xx/certbot-auto/au.sh python txy add" --manual-cleanup-hook "/home/xx/certbot-auto/au.sh python txy clean"

./certbot-auto has insecure permissions!
To learn how to fix them, visit https://community.letsencrypt.org/t/certbot-auto-deployment-best-practices/91979/
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for guanmaicfd.com

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
NOTE: The IP of this machine will be publicly logged as having requested this
certificate. If you're running certbot in manual mode on a machine that is not
your server, please ensure you're okay with that.

Are you OK with your IP being logged?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o:

**Comment by ywdblog** [comment]
点yes就可以，第一次会询问下，后面自动更新证书就不会了

**Comment by junly917** [comment]
好的，我再去试下。
