### ISSUE TITLE
证书还差几个小时更新,这个能提前一天自动续订么?

### ISSUE THREAD

**Issue by hailianghe** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#54]
大神
你好,我们现在用了你的脚本来自动续订,如果每天跑一次的话,会出现几小时或者十几小时证书过期的问题,,比如我们这个证书是晚上19:10过期,我需要19:11跑续订脚本,不能定在0点
![image](https://user-images.githubusercontent.com/29939806/68117451-47d67800-ff38-11e9-9c86-1280ef241d69.png)

**Comment by ywdblog** [comment]
提前30天就能续期，不会出现你说的问题

**Comment by hailianghe** [comment]
非常感谢!!
