### ISSUE TITLE
续期证书后，证书变了，像是申请了一个全新的证书一样

### ISSUE THREAD

**Issue by FlickerMi** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#55]
续期后，cert.pem，privkey.pem变了，像是申请了一个全新的证书一样。

帮忙看看有什么问题吗？
`
./certbot-auto renew  --manual --preferred-challenges dns --manual-auth-hook "/home/root/ops/certbot-letencrypt-wildcardcertificates-alydns-au/au.sh python txy add" --manual-cleanup-hook "/home/root/ops/certbot-letencrypt-wildcardcertificates-alydns-au/au.sh python txy clean"
`

**Comment by FlickerMi** [comment]
@ywdblog

**Comment by ywdblog** [comment]
这是正常的

**Comment by FlickerMi** [comment]
> 这是正常的

@ywdblog  😯，那每次续期后还要手动去更新证书咯？
因为在腾讯云的CDN也使用了此证书，那每次都要去更新证书吗？

**Comment by ywdblog** [comment]
这个工具是更新证书，但将证书自动放到服务器上还要做些工作，比如利用阿里云ecs的api

**Comment by FlickerMi** [comment]
@ywdblog 好的，续期后确实还是需要手动更新，感谢解答我的疑惑。
