### ISSUE TITLE
希望能增加 腾讯云版本的

### ISSUE THREAD

**Issue by sunnyboyi** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#6]
你好，看到你的这个 对 letencrypt 续期 终于有了希望！
对于通配符域名 续期搞了好久 每次都得重头折腾一遍才能行 

由于对php不熟 也没有PHP的调试环境 希望能有个腾讯云版本的
我看了下腾讯云的 请求  很相似，  做一次伸手党，额 .....

**Comment by ywdblog** [comment]
想过支持腾讯云，主要是没有腾讯云的 DNS 服务，我近期弄下吧，PHP 环境基本上很简单，只要有 PHP 命令行环境就可以了（无需 web 服务器）。

**Comment by sunnyboyi** [comment]
@ywdblog 谢谢！ 我会持续关注这个项目的  对了 咱们 还是本家   哈哈  我也姓虞

**Comment by ywdblog** [comment]
python 版本的，已经有同学 PR 支持了，我已经合并进去了，可以了解下。

**Comment by sunnyboyi** [comment]
@ywdblog python  也是支持阿里的  还没支持腾讯的吧

**Comment by ywdblog** [comment]
@sunnyboyi ，腾讯云DNS PHP 操作版已支持。
