### ISSUE TITLE
帮忙看一下阿里云执行脚本出现的问题

### ISSUE THREAD

**Issue by xinghun147** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#64]
Running manual-cleanup-hook command: /root/certbot-letencrypt-wildcardcertificates-alydns-au/au.sh php aly clean
Error output from manual-cleanup-hook command au.sh:
/root/certbot-letencrypt-wildcardcertificates-alydns-au/au.sh: line 1: !/bin/bash: No such file or directory
/root/certbot-letencrypt-wildcardcertificates-alydns-au/au.sh: line 87: /usr/bin/php: No such file or directory

Running manual-cleanup-hook command: /root/certbot-letencrypt-wildcardcertificates-alydns-au/au.sh php aly clean
Error output from manual-cleanup-hook command au.sh:
/root/certbot-letencrypt-wildcardcertificates-alydns-au/au.sh: line 1: !/bin/bash: No such file or directory
/root/certbot-letencrypt-wildcardcertificates-alydns-au/au.sh: line 87: /usr/bin/php: No such file or directory

Some challenges have failed.

请问出现这种报错怎么处理啊？是因为缺少什么环境么？

**Comment by ywdblog** [comment]
/usr/bin/php  有这个php命令行吗
