### ISSUE TITLE
维护新浪 HTTPS 规则到吐血的志愿者求助

### ISSUE THREAD

**Issue by ivysrono** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#9]
虞大胆您好：

我是一名业余规则贡献者，由于被 ISP 劫持过多次，所以大量精力投注在给 HTTPS-Everywhere 扩展写规则上，虽然水平很差，但这几年来被吸纳的规则也超过500条了。现在其[新浪规则](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Sina.com.cn.xml)的架构就是我这两年搭好的。

最近又被 ISP 劫持了次，所以再次开始更新规则。期间发现腾讯、搜狐等都有明显进步，而新浪？怎么说呢，麻烦您来参观下：https://github.com/EFForg/https-everywhere/pull/16355

我们要求真不高，不支持也无所谓，但这样极不稳定，每次测试都随机抛出错误，国内外流量反馈完全不一致，实在是太玄学，太可怕了。

看到您8月6号公众号吐槽了 i0.sinaimg.cn 的问题，我去翻了下，这个坑我早就踩过了啊：https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Sinaimg.cn.xml

我实在是不想继续与玄学问题战斗了，不知能否麻烦您内部推动下？

无论如何，多谢！

**Comment by ywdblog** [comment]
我以前没用过这插件，是说我们新浪的域名列表太多，你哪儿不全?还是说某些域名的https访问有问题？

**Comment by ivysrono** [comment]
关于 HTTPS-Everywhere 的简单介绍可以参考 [维基百科](https://zh.wikipedia.org/wiki/HTTPS_Everywhere)。以下简称 Ew

由于 Ew 内置在 Tor 浏览器等原因，其始终坚持使用静态的规则列表来实现精确的重定向，虽然维护麻烦，但的确性能更好。

EFF 为了保证规则的准确性，采用了 自动测试+人工审核 的做法。所有的规则更新，首先在 Github 提交 PR，待自动测试通过后再进行人工审查。所有支持 HTTPS 而没有进入 HSTS Preload List 的域名都可以写成规则。

我开这个 issue 的原因就是新浪在自动测试时的表现实在是太差劲了。

我最近提交的对新浪的修改 https://github.com/EFForg/https-everywhere/pull/16355 ，本意是将以前不支持而现在支持 HTTPS 的域名加入其中，但基本无法通过测试，原因很简单，大量的新浪域名每一次测试都会有不同的表现，不时抛出错误，每次报错的域名不同，数量不同，甚至同一个域名有时候错误代码都不一样，随便几个例子：

https://travis-ci.org/EFForg/https-everywhere/jobs/418305782#L682
https://travis-ci.org/EFForg/https-everywhere/jobs/418300606#L684
https://travis-ci.org/EFForg/https-everywhere/jobs/418295195#L684
https://travis-ci.org/EFForg/https-everywhere/jobs/418285666#L675

腾讯也有这个问题，国内的大站点多多少少都有点这个问题，但新浪的状况之惨烈，远超其他各家。

您在微信里吐槽的 i0.sinaimg.cn 的坑，我今年四月就踩过了：https://travis-ci.org/EFForg/https-everywhere/jobs/362611354#L732

所以在关于 Sinaimg.cn 的[规则](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Sinaimg.cn.xml)里，我将 i[0-3].sinaimg.cn 都重定向到了 i[0-3]s.sinaimg.cn 版本，否则无法通过自动测试啊。至于 henan.sinaimg.cn 这种神奇的域名不支持 HTTPS 都不算事了。

作为 Ew 国区规则的主要维护这之一，我最大的梦想就是各大站点都进入 HSTS Preload List，因此删规则最爽了。

实际上我知道新浪这种大站点需要维护大量低版本浏览器客户，那没关系，客户至上那是理所当然的；

如果能提供充分的选择空间，那就很好了，像京东，默认都没有启用 HTTPS，但我可以写规则啊——顺便一说，京东的域名那才叫多，多到写在一个规则里的话自动测试一个小时都跑不完，但支持程度相当不错；

如果只能对静态资源提供 HTTPS 也行，配合我维护的另一个[扩展规则](https://github.com/ivysrono/UpgradeMixedContentBlacklist)解决 MixedContentBroken ，在用户体验上也可以接受。

作为一个外人我无法妄自揣测无法通过自动测试的原因是什么，您是 HTTPS 问题的专家，水平不知道比我高到哪里去了，相信已经明白我的大概意思了。

看到您写的新浪邮箱全面支持 HTTPS 的文章的转载，顺藤摸瓜找到这寻求帮助，冒昧打扰，还请见谅。

**Comment by ywdblog** [comment]
我看了你举的测试用例：

1：beacon.sina.com.cn 403 的问题，这个域名应该有客户端加密处理，如果直接访问域名（不管 80 还是 443），这个都会返回 403，我的意思是这个应该不能简单的转换为 443（至少在测试用例中看到的是这样的）。
2：我也看了几个今天的测试报错。
（1）很多是超时，这个一方面和 443 没有关系，只能说明我们某些服务可能服务不稳定（或者遇到网络问题）
（2）另外有些域名做了很多重定向，比如 mail2008.sina.com.cn ，导致的一些返回错误，这可以说是域名（或者业务）使用的比较混乱，有些业务历史太旧了，其实和 443 没有关系。

关于你提到的一些猜测：
1：一般情况下，不会拦截请求，尤其不会在 ssl 交互的时候。

关于你说的静态资源，我们公司有专门团队维护，在部署新的点，或者支持阿里云 CDN 上犯了一些错误，包括像 i0 这样的域名也逐步弱化，可能关注度不够，不过整体上应该是没有大问题。

以上是我简单看到的一些情况，我的意思是，测试脚本可能不能仅仅根据域名做测试用例，了解不多，不知道对不对。

如果针对具体某个主机访问遇到问题，你可以告诉我，我反馈一下。

祝好。

**Comment by gloomy-ghost** [comment]
CI 检测错误码主要是担心有些网站有 https 但没配内容，防止升级到 https 把原来正常的请求给弄挂了得不偿失。因此测试逻辑是在 http 正常时才对 https 返回的错误码反应，如果 http 也是 403 的话反而不会有事，见 [EFForg/https-everywhere/test/rules/src/https_everywhere_checker/check_rules.py#L157](https://github.com/EFForg/https-everywhere/blob/770bdfa645738ff9c7d25577d328fc6f7397fbe2/test/rules/src/https_everywhere_checker/check_rules.py#L157)。

我能确定的是新浪节点之间行为不一致，比如这样的：
https://gist.github.com/gloomy-ghost/f9fce9fc671adf91c4cbc4653f67a9fe

顺便关于公众号文中提到的 360 浏览器，我没环境测试但可以猜一下，看描述来说估计是 360 没用系统 DNS，请求到了其他节点上而已。如果 https 不可用自动降级到 http 的话 360 也太坑了（虽然无视证书错误也一样坑……）

**Comment by ywdblog** [comment]
1：beacon.sina.com.cn 是一个类似数据统计的服务，一会 403，一会 200 应该是应用层的策略。我觉得这个测试的时候，加个特殊处理把。
2：节点不一致的主要是静态资源的CDN，其他的Host，是因为一些服务质量不过关等原因导致的，这个一时半会很难搞定。而 CDN 出过一些问题，我也反馈一下，不过整体上 443 应该是没啥问题的，其实 i0 i1 这样的域名，可以统一重定向到 www.sinaimg.cn 
3：360 那个后来我琢磨了下，是他自己做了一份缓存，所以实际上没有发出真正的静态资源443请求。

**Comment by ivysrono** [comment]
多谢。
我更新了下 PR，暂时幸运地通过了测试，还是有几个问题要请教下：
r[1-3].sinaimg.cn 和 u1.sinaimg.cn 这些域名是不支持了？查了下外链虽然不多还是有一点的。
henan.sinaimg.cn 这个域名是否不支持 https？
d[0-9].sina.com.cn 极不稳定，典型的随机抛错，不知是何原因。
iask.sina.com.cn 似乎也会随机抛错，参见 https://travis-ci.org/EFForg/https-everywhere/jobs/419086077#L684 。
烦请查下。

**Comment by ywdblog** [comment]
不好意思啊，很多服务我也不是很清楚是干什么的了。

感谢关注！
